//These are all of the different types of items available to be picked up

package IT4;

/**
 *
 * @author Jim (Admin)
 */

//SECONDARY_SILENCER = SILENCER, PRIMARY_SILENCER = SMG_SILENCER, TRANQ_PISTOL = WRISTWATCH
public enum ItemType {MEDKIT, SECONDARY_AMMO, PRIMARY_AMMO, SECONDARY_MAG, PRIMARY_MAG, TRANQ_PISTOL, PISTOL, ASSAULT_RIFLE, SECONDARY_SILENCER,
                      CARDKEY_1, CARDKEY_2, CARDKEY_3, CARDKEY_4, CARDKEY_5, CARDKEY_6, CARDKEY_7, CARDKEY_8, CARDKEY_9, CARDKEY_10,
                      BOOSTER_KIT, SMG, SHOTGUN, GRENADE, GASMASK, NVG, BODY_ARMOR, PRIMARY_SILENCER, LANDMINE, LASER_HORIZONTAL, LASER_VERTICAL, MINE_DETECTOR, C4, KNIFE}
