/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainMenuFrame.java
 *
 * Created on Feb 25, 2012, 10:41:03 PM
 */

package IT4;

//import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
//import org.lwjgl.opengl.Display;

/**
 *
 * @author Jim
 */
public class MainMenuFrame extends javax.swing.JFrame
{
    private MainMenuPanel mmp;

    /** Creates new form MainMenuFrame */
    public MainMenuFrame()
    {
        initComponents();
        mmp = new MainMenuPanel(this);
        this.add(mmp);
        this.setVisible(true);
        mmp.setVisible(true);

        BufferedImage source = null;

        try
        {
            URL url = this.getClass().getClassLoader().getResource("Sprites/IT4Icon.gif");

            if (url == null)
            {
                System.out.println("Bad filename : ref = " + "Sprites/IT4Icon.gif");
            }

            source = ImageIO.read(url);

        }
        catch (IOException e)
        {
            System.out.println("Intruder's Thunder: IO Exception");
        }

        this.setIconImage(source);
    }

    public MainMenuFrame(Dialog d)
    {
        //JOptionPane.showMessageDialog(null, d.toString(), d.title, JOptionPane.PLAIN_MESSAGE);

        initComponents();
        mmp = new MainMenuPanel(this);
        this.add(mmp);
        this.setVisible(true);
        mmp.setVisible(true);

        BufferedImage source = null;

        try
        {
            URL url = this.getClass().getClassLoader().getResource("Sprites/IT4Icon.gif");

            if (url == null)
            {
                System.out.println("Bad filename : ref = " + "Sprites/IT4Icon.gif");
            }

            source = ImageIO.read(url);

        }
        catch (IOException e)
        {
            System.out.println("Intruder's Thunder: IO Exception");
        }

        this.setIconImage(source);        

        JOptionPane.showMessageDialog(null, d.toString(), d.title, JOptionPane.PLAIN_MESSAGE);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("The Endling's Artifice");
        setName(""); // NOI18N
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
